<a href="https://colab.research.google.com/github/sagarkakkar03/Practice/blob/main/NumPy_Assignment_Array_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Assignment – Array Operations & Indexing

## Instructions
1. Use NumPy only
2. Do NOT use loops unless explicitly required
3. Write clean, readable code
4. Print output for each question

In [2]:
import numpy as np

## Section A: Array Creation & Reshaping

In [3]:
# Q1: Create a 1D array from 1 to 12 and reshape it into a 3x4 array
arr = np.arange(12).reshape(3, 4)

In [4]:
# Q2: Create a 2D array of shape (4,3) using arange() and reshape it into (2,2,3)
arr2d = np.arange(1, 13).reshape(4, 3)
arr3d = arr2d.reshape(2, 2, 3)
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
# Q3: Create a 3x3 array, ravel it, modify the raveled array,
#     and check if the original array changes
arr3d = np.arange(9).reshape(3,3)
arr3d
arr3d_ravel = arr3d.ravel()
arr3d_ravel[0]=100
arr3d

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8]])

In [9]:
# Q4: Create a 1D array of size 9 and convert it into:
#     a) 2D array (3x3)
#     b) matrix object
mat = np.matrix(np.arange(9).reshape(3, 3))
mat

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [14]:
# Q5: Create a 3x4 array, print its shape,
#     reshape it to 4x3, and flatten it back to 1D
arr = np.arange(12)
arr.reshape(4, 3).flatten()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Section B: Indexing & Slicing

In [19]:
arr = np.arange(1, 17).reshape(4, 4)
# Q6: Extract:
# a) Second row
# b) Third column
# c) Element at position (2,3)
print(arr)
arr[2, 3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


np.int64(12)

In [20]:
# Q7: Extract the sub-matrix [[6,7],[10,11]]
arr[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [21]:
# Q8: Reverse:
# a) All rows
# b) All columns
arr[::-1, ::-1]

array([[16, 15, 14, 13],
       [12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [22]:
# Q9: Extract all even numbers from the array
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [23]:
# Q10: Replace all elements greater than 10 with -1
arr[arr>10] = -1

## Section C: Fancy Indexing

In [ ]:
# Q11: Using fancy indexing, extract indices [0,3,5,7]
# from a 1D array of size 10

In [24]:
arr2 = np.arange(1, 26).reshape(5, 5)
# Q12: Extract diagonal elements using fancy indexing
arr2[[0, 1, 2, 3, 4], [0, 1,2, 3, 4]]

array([ 1,  7, 13, 19, 25])

In [ ]:
# Q13: Using row and column index arrays, extract [1,7,13,19,25]


In [25]:
# Q14: Swap Row 1 and Row 3 using fancy indexing
arr2[[1, 3],:] = arr2[[3, 1], :]

array([[ 1,  2,  3,  4,  5],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25]])

## Section D: Conditional & Logical Operations

In [26]:
# Q15: Create a 1D array from 1 to 20 and extract numbers >5 and <=15
arr = np.arange(1, 21)
arr[(arr>5)&(arr<=15)]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
# Q16: From a 2D array, extract elements that are even AND greater than 10
arr[(arr%2==0) & (arr>10)]

array([12, 14, 16, 18, 20])

In [ ]:
# Q17: Replace all odd numbers in an array with 0

In [29]:
# Q18: Count how many elements are greater than the mean of the array
arr[arr>arr.mean()]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])
# Q19:
# a) Common elements
# b) Elements in A but not in B
np.intersect1d(A, B)
np.setdiff1d(A, B)

array([1, 2])

In [ ]:
arr3 = np.array([
    [12, 7, 5],
    [3, 20, 15],
    [8, 10, 2]
])
# Q20:
# 1. Extract values > 8
# 2. Replace values < 5 with -99
# 3. Return result as a 1D array