<a href="https://colab.research.google.com/github/sagarkakkar03/Practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.arange(4)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.ndim

1

In [6]:
arr.shape

(4,)

In [7]:
list2 = np.array([(1, 2, 3), (3, 4,5)])

In [8]:
arr2 = np.arange(4)

In [9]:
arr*arr2

array([0, 1, 4, 9])

In [10]:
arr + arr2

array([0, 2, 4, 6])

In [11]:
mat = np.matrix(arr)

In [12]:
type(mat)

numpy.matrix

In [13]:
mat.ndim

2

In [14]:
mat.shape

(1, 4)

In [22]:
mat

matrix([[0, 1, 2, 3]])

In [23]:
mat2 = np.matrix([[0], [1], [2], [3]])
mat2

matrix([[0],
        [1],
        [2],
        [3]])

In [21]:
mat3 = mat*mat2
mat3

matrix([[14]])

In [32]:
mat2 = mat2.ravel()

In [34]:
mat2.shape

(1, 4)

In [29]:
arr2d = np.array([[1,2], [3, 4]])
arr2d.ravel()

array([1, 2, 3, 4])

In [30]:
arr.reshape(2,2)

array([[0, 1],
       [2, 3]])

In [31]:
mat2.reshape(2,2)

matrix([[0, 1],
        [2, 3]])

In [41]:
mat2[0, 1]

np.int64(1)

In [45]:
mat2[0, :2]

matrix([[0, 1]])

In [49]:
matrix = np.matrix([[1,2,3],[4,5,6], [7,8,9]])

In [53]:
matrix[[1,2], [0,0]].reshape(2, 1)

matrix([[4],
        [7]])

In [54]:
array = np.arange(25).reshape(5, 5)

In [55]:
11 in array

True

In [56]:
array > 11

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [57]:
array[array > 11]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
array[(array > 11) & (array % 2)]

array([[[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4]]])

In [62]:
np.arange(1, 11, dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [64]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [66]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [93]:
count = 0
arr = np.random.normal(loc=0, scale=1, size=100000)
print(arr.mean(), arr.std())

0.00256959755613284 0.9969029432783808


In [95]:
arr = np.random.rand(10000)
print(arr.mean(), arr.var())

0.5000566185066718 0.08444986834858739


In [96]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])